# Change these first
owner: DFE-Digital # Your GitHub organization or username, where this repository lives
repo: teacher-services-upptime # The name of this repository

sites:
  - name: Access your teaching qualifications
    url: https://access-your-teaching-qualifications.education.gov.uk/health/all
  - name: Apply for qualified teacher status
    url: https://apply-for-qts-in-england.education.gov.uk/healthcheck
  - name: Apply for teacher training
    url: https://www.apply-for-teacher-training.service.gov.uk/integrations/monitoring/all
  - name: Check a teacher's record
    url: https://check-a-teachers-record.education.gov.uk/health
  - name: Check the children's barred list
    url: https://check-the-childrens-barred-list.education.gov.uk/healthcheck
  - name: Claim Additional Payments for Teachers
    url: https://claim-additional-teaching-payment.service.gov.uk/healthcheck
  - name: Claim funding for mentor training
    url: https://claim-funding-for-mentor-training.education.gov.uk/healthcheck/all
  - name: Find a lost TRN
    url: https://find-a-lost-trn.education.gov.uk/health
  - name: Find a Teaching School Hub
    url: https://find-a-teaching-school-hub.education.gov.uk/healthcheck
  - name: Find teacher training courses
    url: https://find-teacher-training-courses.service.gov.uk/healthcheck
  - name: Find postgraduate teacher training
    url: https://www.find-postgraduate-teacher-training.service.gov.uk/healthcheck
  - name: Get a Teacher Relocation Payment
    url: https://get-a-teacher-relocation-payment.education.gov.uk/healthcheck/all
  - name: Get into teaching
    url: https://getintoteaching.education.gov.uk/
  - name: Get into teaching - API
    url: https://getintoteachingapi-production.teacherservices.cloud/api/operations/health_check
  - name: Manage Teacher CPD
    url: https://manage-training-for-early-career-teachers.education.gov.uk/healthcheck
  - name: Professional development for teachers and leaders
    url: http://professional-development-for-teachers-leaders.education.gov.uk/
  - name: Publish teacher training courses
    url: https://www.publish-teacher-training-courses.service.gov.uk/healthcheck
  - name: Refer serious misconduct
    url: https://refer-serious-misconduct.education.gov.uk/health/all
  - name: Register For a National Professional Qualification
    url: https://register-national-professional-qualifications.education.gov.uk/healthcheck
  - name: Register trainee teachers
    url: https://www.register-trainee-teachers.education.gov.uk/
  - name: School Experience
    url: https://schoolexperience.education.gov.uk/healthcheck
  - name: Support For Early Career Teachers
    url: https://support-for-early-career-teachers.education.gov.uk/
  - name: Teaching Identity
    url: https://teaching-identity.education.gov.uk/status
  - name: Teaching Record System / Teacher Qualifications API
    url: https://teacher-qualifications-api.education.gov.uk/status
  - name: Teacher training API
    url: https://api.publish-teacher-training-courses.service.gov.uk/healthcheck
  - name: Teaching Vacancies
    url: https://teaching-vacancies.service.gov.uk/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: teacher-services-status.education.gov.uk
  name: Teacher services status
  introTitle: Status of all digital services in **Teacher services**
  introMessage: |
    This website is in **beta**.
    It aims to show the status of each service in Teacher services and log potential downtimes, but false alarms may still happen.
    Updated every 5 min.
  navbar:
    - title: Status
      href: https://teacher-services-status.education.gov.uk
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
