# Change these first
owner: DFE-Digital # Your GitHub organization or username, where this repository lives
repo: teacher-services-upptime # The name of this repository

sites:
  - name: Get into teaching
    url: https://getintoteaching.education.gov.uk/
  - name: Get into teaching - Adviser
    url: https://adviser-getintoteaching.education.gov.uk/
  - name: Get into teaching - API
    url: https://getintoteachingapi-production.teacherservices.cloud/api/operations/health_check
  - name: School Experience
    url: https://schoolexperience.education.gov.uk/healthcheck
  - name: Register trainee teachers
    url: https://www.register-trainee-teachers.education.gov.uk/
  - name: Find postgraduate teacher training
    url: https://www.find-postgraduate-teacher-training.service.gov.uk/healthcheck
  - name: Publish teacher training courses
    url: https://www.publish-teacher-training-courses.service.gov.uk/healthcheck
  - name: Apply for teacher training
    url: https://www.apply-for-teacher-training.service.gov.uk/integrations/monitoring/all
  - name: Teacher training API
    url: https://api.publish-teacher-training-courses.service.gov.uk/healthcheck
  - name: Teaching Vacancies
    url: https://teaching-vacancies.service.gov.uk/
  - name: Manage Teacher CPD
    url: https://manage-training-for-early-career-teachers.education.gov.uk/healthcheck
  - name: Claim Additional Payments for Teachers
    url: https://claim-additional-teaching-payment.service.gov.uk/healthcheck
  - name: Qualified Teachers API
    url: https://teacher-qualifications-api.education.gov.uk/status
  - name: Find a lost TRN
    url: https://find-a-lost-trn.education.gov.uk/health
  - name: Apply for QTS
    url: https://apply-for-qts-in-england.education.gov.uk/healthcheck
  - name: Get a Teacher Relocation Payment
    url: https://get-a-teacher-relocation-payment.education.gov.uk/healthcheck/all
  - name: Access Your Teaching Qualification
    url: https://access-your-teaching-qualifications.education.gov.uk/health/all
  - name: Register For a National Professional Qualification
    url: https://register-national-professional-qualifications.education.gov.uk/healthcheck
  - name: Find a Teaching School Hub
    url: https://find-a-teaching-school-hub.education.gov.uk/healthcheck
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: teacher-services-status.education.gov.uk
  logoUrl: https://assets.apply-for-teacher-training.service.gov.uk/packs/media/images/govuk-crest-2x-05968778.png
  favicon: https://api.publish-teacher-training-courses.service.gov.uk/favicon.ico
  name: Teacher services status
  introTitle: Status of all digital services in **Teacher services**
  introMessage: |
    This website is in **beta**.
    It aims to show the status of each service in Teacher services and log potential downtimes, but false alarms may still happen.
    Updated every 5 min.
  navbar:
    - title: Status
      href: /teacher-services-upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
